### ISSUE TITLE
能支持其他的TCP应用嘛？

### ISSUE THREAD

**Issue by triumph** [movsb/http2tcp#3]
能支持其他的TCP应用嘛？ 比如 mysql ， mongo  ， redis  等等

**Comment by triumph** [comment]
如果支持的，需要怎么做呢？

**Comment by movsb** [comment]
所有基于 TCP 的应用都支持，`-d` 参数指向目标端口就可以了。

**Comment by AcosX** [comment]
其他应用的话，客户端打开后怎么做？是直接让应用访问localhost对应端口吗？

**Comment by movsb** [comment]
@AcosX  是的，如果是用标准输入输出交互的话，本地不用加 `-l` 参数（用作 ssh ProxyCommand 的场景，单个连接/单个进程的场景）。如果是要支持多路连接的话，本地也指定一下 `-l` 参数，然后应用访问这个参数的地址就行。
